#!/bin/sh

set -e

usage() { echo "Usage: $0 [-d postgres database] [-p postgres port]" 1>&2; exit 1; }

while getopts ":d:p:" opt; do
  case $opt in
    d)
      dbname=$OPTARG
      ;;
    p)
      port=$OPTARG
      ;;
    *)
      usage
      ;;
  esac
done

shift $((OPTIND-1))

if [ -z "${dbname}" ]; then
  usage
fi

red="\033[31m"
nc="\033[m"

# Check to ensure we have all the proper dependencies
echo "\n${red}Checking to make sure you've got everything you need...${nc}"
script/dependencies-check

# Download all the require data we need to process everything
echo "\n${red}Downloading and converting metro data...${nc}"
make --quiet all

# Drop and recreate database, but ask for confirmation first.
echo "\n${red}Creating postgres database...${nc}"
dropdb --if-exists --interactive -e $dbname
createdb --encoding UTF8 $dbname

# Create the POSTGIS and HSTORE extensions
psql -d $dbname -c 'create extension postgis; create extension hstore'

# Import shapefiles to our newly created database
echo "\n${red}Importing shapefile data into postgres...${nc}"
for file in shp/buildings.shp shp/addresses.shp shp/precincts.shp; do \
  filename=$(basename $file)
  tablename=${filename%.*}
  shp2pgsql -t 2D  -I -D -d -s 4326 -W "latin1" -g geom $file $tablename | psql -d $dbname
done

# Import existing OSM data
echo "\n${red}Importing existing OSM data into postgres...${nc}"
osm2pgsql -S config/osm-default.style --database $dbname --port $port osm/features.osm.bz2
