#!/bin/sh

set -e

usage() { echo "Usage: $0 [-d postgres database]" 1>&2; exit 1; }

while getopts ":d:p:" opt; do
  case $opt in
    d)
      dbname=$OPTARG
      ;;
    p)
      port=$OPTARG
      ;;
    *)
      usage
      ;;
  esac
done

shift $((OPTIND-1))

if [ -z "${dbname}" ]; then
  usage
fi

red="\033[31m"
nc="\033[m"

echo "\n${red}Loading custom postgres helper functions...${nc}"
psql -d $dbname -f sql/_normalize_state_id.sql
psql -d $dbname -f sql/_expandcardinal_dir_.sql

echo "\n${red}Converting addresses to OSM-friendly format...${nc}"
psql -d $dbname -f sql/finalize-addresses.sql

echo "\n${red}Joining buildings with OSM friendly addresses...${nc}"
psql -d $dbname -f sql/finalize-buildings.sql
